# Generated by Django 2.1.5 on 2019-01-12 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_auto_20190112_0806'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemagenda',
            options={'verbose_name': 'Tarefa Agendada', 'verbose_name_plural': 'Item agendas'},
        ),
    ]
